# <CENTER> PANDAS DATA INTEGRATION AND TRANSFORMATION

## MERGING DATA USING PANDAS

### Basic Merging:

In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame({"id":[1,2,3],
                  "Name":["Aisha","Binu","Cathy"]})
df2=pd.DataFrame({"id":[1,2,4],
                  "Mark":[85,90,75]})
merged_df=pd.merge(df1,df2,on="id")
print(merged_df)

   id   Name  Mark
0   1  Aisha    85
1   2   Binu    90

## <center> TYPES OF JOINS

## INNER JOIN(Default)

### Only Common Rows:

In [4]:
pd.merge(df1,df2,on="id",how="inner")

   id   Name  Mark
0   1  Aisha    85
1   2   Binu    90

## LEFT JOIN

### All Rows from Left DataFrame And Common from Right:

In [6]:
pd.merge(df1,df2,on="id",how="left")

   id   Name  Mark
0   1  Aisha  85.0
1   2   Binu  90.0
2   3  Cathy   NaN

## RIGHT JOIN

### All Rows from Right DataFrame And Common from Left:

In [7]:
pd.merge(df1,df2,on="id",how="right")

   id   Name  Mark
0   1  Aisha    85
1   2   Binu    90
2   4    NaN    75

## OUTER JOIN

### All Rows from Both:

In [8]:
pd.merge(df1,df2,on="id",how="outer")

   id   Name  Mark
0   1  Aisha  85.0
1   2   Binu  90.0
2   3  Cathy   NaN
3   4    NaN  75.0

## <CENTER> MERGE ON DIFFERENT COLUMN NAMES:

In [26]:
df1=pd.DataFrame({"id":[1,2,3],
                  "Name":["Aisha","Binu","Cathy"]})
df2=pd.DataFrame({"student_id":[1,2,4],
                  "Mark":[85,90,75]})
merged_df=pd.merge(df1,df2,left_on="id",right_on="student_id")
print(merged_df)

   id   Name  student_id  Mark
0   1  Aisha           1    85
1   2   Binu           2    90

In [27]:
l_merge=pd.merge(df1,df2,left_on="id",right_on="student_id",how="left")
l_merge

   id   Name  student_id  Mark
0   1  Aisha         1.0  85.0
1   2   Binu         2.0  90.0
2   3  Cathy         NaN   NaN

In [29]:
r_merge=pd.merge(df1,df2,left_on="id",right_on="student_id",how="right")
r_merge

    id   Name  student_id  Mark
0  1.0  Aisha           1    85
1  2.0   Binu           2    90
2  NaN    NaN           4    75

In [31]:
o_merge=pd.merge(df1,df2,left_on="id",right_on="student_id",how="outer")
o_merge

    id   Name  student_id  Mark
0  1.0  Aisha         1.0  85.0
1  2.0   Binu         2.0  90.0
2  3.0  Cathy         NaN   NaN
3  NaN    NaN         4.0  75.0

## <CENTER> CONCATENATION

In [32]:
pd.concat([df1,df2],axis=0)

    id   Name  student_id  Mark
0  1.0  Aisha         NaN   NaN
1  2.0   Binu         NaN   NaN
2  3.0  Cathy         NaN   NaN
0  NaN    NaN         1.0  85.0
1  NaN    NaN         2.0  90.0
2  NaN    NaN         4.0  75.0

In [33]:
pd.concat([df1,df2],axis=1)

   id   Name  student_id  Mark
0   1  Aisha           1    85
1   2   Binu           2    90
2   3  Cathy           4    75

## <CENTER> APPLY

In [35]:
Marks=pd.Series([45,60,75,90])
def grade(x):
    if x>=50:
        return "Pass"
    else:
        return "Fail"
print(Marks.apply(grade))

0    Fail
1    Pass
2    Pass
3    Pass
dtype: str

### Apply Using Lambda Function:

In [36]:
Marks=pd.Series([45,60,75,90])
result=Marks.apply(lambda x:x+5)
print(result)

0    50
1    65
2    80
3    95
dtype: int64

### Apply() On DataFrame Columns:

In [37]:
df=pd.DataFrame({"Math":[80,70,90],
                 "Science":[85,60,95]})
print(df.apply(max))

Math       90
Science    95
dtype: int64

In [38]:
print(df.apply(min))

Math       70
Science    60
dtype: int64